kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developers-objectbucketclaims
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaims"]
    verbs:
      - '*'
