#oc adm policy add-role-to-group admin dev01 --rolebinding-name=hello --dry-run=client -o yaml
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: groupadmins-dev01
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: dev01

