apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:
  applicationSet:
    resources:
      limits:
        cpu: "300m"
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  controller:
    processors: {}
    resources:
      limits:
        cpu: "300m"
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    sharding: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: "300m"
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    route:
      enabled: false
  ha:
    enabled: false
    resources:
      limits:
        cpu: "300m"
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: ""
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'
  redis:
    resources:
      limits:
        cpu: "300m"
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: "300m"
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: "300m"
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    route:
      enabled: true
    service:
      type: ""
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 300m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    provider: dex
  tls:
    ca: {}