#oc adm policy add-cluster-role-to-user kyverno-added-privileges system:serviceaccount:kyverno:kyverno-background-controller -o yaml --dry-run=client
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-added-privilege-watch-clusterresourcequotas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-added-privilege-watch-clusterresourcequotas
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:kyverno:kyverno-admission-controller
- kind: ServiceAccount
  name: kyverno-admission-controller
  namespace: kyverno
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:kyverno:kyverno-background-controller
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
