apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitops-namespace-policy.yaml
  - label-and-annotate-namespaces-policy.yaml
  - maxsize-bucket-policy.yaml
  - restrict-namespace-names-policy.yaml
  - sandbox-namespace-policy.yaml
  - networkpolicies-policy.yaml