apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- assets/gitops-namespace-policy.yaml
- assets/label-and-annotate-namespaces-policy.yaml
- assets/maxsize-bucket-policy.yaml
- assets/restrict-namespace-names-policy.yaml
- assets/sandbox-namespace-policy.yaml
- assets/networkpolicies-policy.yaml

patches:
- target:
    kind: ClusterPolicy
    name: gitops-namespace
  path: patches/small-gitops.yaml